### ISSUE TITLE
A lot of spam in the log

### ISSUE THREAD

**Issue by timliesenhoff** [yzzuf/cr_degradation#1]
its all starting with:
`script:vorp_inventor] SCRIPT ERROR: @vorp_inventory/server/services/inventoryApiService.lua:663: attempt to index a nil value (local 'item')
[script:vorp_inventor] > ref (@vorp_inventory/vorpInventoryApi.lua:191)
[script:vorp_inventor] > handler (@cr_degradation/server/server.lua:27)`

and repeating.

but with actuall version mainly it works

**Comment by yzzuf** [comment]
Update your inventory

**Comment by timliesenhoff** [comment]
ill do!

**Comment by timliesenhoff** [comment]
Its all fine, thank you!
